package com.illam.chiya.enums;

public enum Tags {
	// Food Type & Base
	FERMENTED, DRIED, PICKLED, CHUTNEY, CURRY_BASE, INSTANT, HANDMADE, SUN_DIED, ROASTED, HOMEMADE,

	// Primary Ingredients
	GUNDRUK, TAMA, CHUK, DAL, RICE, BEANS, MAIZE, WHEAT, MILLET, BUCKWHEAT,

	// Flavor Profile
	SPICY, SOUR, SWEET, UMAMI, SMOKY, BITTER, MILD, TANGY, STRONG_FLAVOR, NEUTRAL_FLAVOR,

	// Herbs, Spices & Additives
	TIMBUR, GINGER, GARLIC, TURMERIC, ASAFOETIDA, JIMBU, CHILLI, CUMIN, CLOVES, CARDAMOM,

	// Beverage Types
	BLACK_TEA, GREEN_TEA, HERBAL_TEA, SALTY_TEA, MILK_TEA, BUTTER_TEA, FERMENTED_DRINK, AYURVEDIC_TEA, CAFFEINE_FREE,
	MORNING_TEA,

	// Use & Consumption Style
	SNACK, SIDE_DISH, MAIN_COURSE, BREAKFAST, DINNER, WITH_RICE, WITH_ROTI, WITH_BREAD, WITH_BEVERAGE,
	COOKING_INGREDIENT,

	// Health & Diet
	VEGAN, VEGETARIAN, PROTEIN_RICH, LOW_CALORIE, ENERGY_BOOST, IMMUNITY_BOOST, DIGESTION_FRIENDLY, COLD_RELIEF, DETOX,
	ANTI_INFLAMMATORY,

	// Spice & Heat Level
	MILD_SPICE, MEDIUM_SPICE, HOT, EXTREME_HEAT, KIDS_FRIENDLY, SENSITIVE_STOMACH,

	// Origin / Regional
	KATHMANDU_VALLEY, EASTERN_HILLS, WESTERN_HILLS, TERAI, HIMALAYAN_REGION, GURUNG_STYLE, TAMANG_STYLE, THAKALI_STYLE,
	NEWARI_STYLE, RAI_LIMBU_STYLE,

	// Season & Occasion
	WINTER_SPECIAL, SUMMER_SPECIAL, FESTIVAL_ITEM, DASHIAN_ITEM, TIHAR_ITEM, MARRIAGE_ITEM, PICKLE_SEASON,
	MONSOON_COMFORT, COLD_WEATHER, YEAR_ROUND,

	// Target Users / Mood
	FOR_KIDS, FOR_ELDERLY, FOR_TRAVEL, COMFORT_FOOD, QUICK_MEAL, HEAVY_MEAL, TRADITIONAL_RECIPE, MODERN_TWIST,
	PARTY_ITEM, DAILY_USE
}
